### PR TITLE
Hotfox/allow external fix

### PR DESCRIPTION
**Pull request by ericyz**

### CODE REVIEW

**Comment by ahmetb** [comment]
I'm trying to understand what this fixes, was there an API validation error?

The `networkpolicy.spec.ingress` field seems to be an ` []Object` type, so

      ingress:
      - from: []

seems to conform to the API as well.

Furthermore, the array's 0th values `{}` and `from: []` both seem to have the same effect according to `ingress` field doc (we just need at least 1 element here, and `{}` and `from: []` do the same thing).

>    List of ingress rules to be applied to the selected pods. Traffic is
     allowed to a pod if there are no NetworkPolicies selecting the pod (and
     cluster policy otherwise allows the traffic), OR if the traffic source is
     the pod's local node, OR if the traffic matches at least one ingress rule
     across all of the NetworkPolicy objects whose podSelector matches the pod.
     If this field is empty then this NetworkPolicy does not allow any traffic
     (and serves solely to ensure that the pods it selects are isolated by
     default)

**Comment by ahmetb** [comment]
I just saw the context at #71. `networkpolicy.spec.ingress.from` docs say:

> DESCRIPTION:
     List of sources which should be able to access the pods selected for this
     rule. Items in this list are combined using a logical OR operation. **If this
     field is empty or missing, this rule matches all sources (traffic not
     restricted by source).** If this field is present and contains at least one
     item, this rule allows traffic only if the traffic matches at least one
     item in the from list.

According to this description, I don't think `from: []` blocks everything according to the **bold** section above.

Is `[]` value not considered "empty"? Have we tested this @boredabdel?

**Comment by boredabdel** [comment]
Yes so https://github.com/ahmetb/kubernetes-network-policy-recipes/pull/71 was proposing a change that would not work (replacing [] with {}) so i rejected it.

This new PR made sense to me as it matches the Kubernetes.io doc example https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-allow-all-ingress-traffic

Having the 

`
from: [] 
`
section or not having is the same thing essentially

**Comment by boredabdel** [comment]
Note that  we don't have the **policyTypes** field which is implicit according to the kubernetes.io doc

> policyTypes: Each NetworkPolicy includes a policyTypes list which may include either Ingress, Egress, or both. The policyTypes field indicates whether or not the given policy applies to ingress traffic to selected pod, egress traffic from selected pods, or both. If no policyTypes are specified on a NetworkPolicy then by default Ingress will always be set and Egress will be set if the NetworkPolicy has any egress rules.

**Pull request merged**
