### PR TITLE
Extend example to emphasize port names are also supported

### PR DESCRIPTION
**Pull request by pdecat**
> port :	The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers.

https://kubernetes.io/docs/api-reference/v1.9/#networkpolicyport-v1-networking

### CODE REVIEW

**Comment by ahmetb** [comment]
thanks!

**Comment by pdecat** [comment]
You're welcome :)

Maybe it would be also worth noting that the protocol defaults to TCP if not specified.

**Comment by ahmetb** [comment]
eh, you're right. but this repo isn't trying to be the definitive documentation :)

**Comment by pdecat** [comment]
Just saying because we occur to push our metrics over UDP (statsd).

**Pull request merged**
